version: '3.9'
services:
  stopwatch:
    container_name: Stopwatch
    pull_policy: build
    build: .
    volumes:
      - type: bind
        source: /var/log/brackeysbot/stopwatch
        target: /app/logs
      - type: bind
        source: /etc/brackeysbot/stopwatch
        target: /app/data
    restart: always
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
